### ISSUE TITLE
Newline outside marbleblock results in newline

### ISSUE THREAD

**Issue by AdeRegt** [nibblebits/marble#4]
Example:
<script>
window.alert("doh!/nI'm a bug <marble>IO.Print("oh no");</marble>"):
</script>

Results in my browser in a syntaxerror:
I'm a bug is on a new line.

**Comment by nibblebits** [comment]
Thanks for your issue report. This is not an issue with Marble and is simply a syntax error in your javascript code. To call IO.Print inside window.alert you must put marble tags so your code should actually look like this

`<script> window.alert("doh!/nI'm a bug <marble>IO.Print("oh no");</marble>"): </script> `

**Comment by nibblebits** [comment]
You would get a new line with "\n" as your using javascript

**Comment by nibblebits** [comment]
Issue reopened as bug is present for anything outside of marble tags
`hello\nworld` results in hello then a new line then world.
Bug will be resolved shortly

**Comment by nibblebits** [comment]
Bug fixed: https://github.com/nibblebits/marble/commit/8e3a2f4b4d3fcd7fdb82fa0dffe4fa1e6e0dd8af
I shall release a patch shortly
